// <auto-generated />
namespace SakaryaRehberiAPI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class tf1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tf1));
        
        string IMigrationMetadata.Id
        {
            get { return "201604231640461_tf1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
