// <auto-generated />
namespace SakaryaRehberiAPI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class tf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tf));
        
        string IMigrationMetadata.Id
        {
            get { return "201604221305167_tf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
