//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakaryaRehberiAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComment
    {
        public int UserComment_ID { get; set; }
        public int User_ID { get; set; }
        public int Location_ID { get; set; }
        public string UserComment_Comment { get; set; }
        public System.DateTime UserComment_Date { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual User User { get; set; }
    }
}
