//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakaryaRehberiAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public User()
        {
            this.UserComments = new HashSet<UserComment>();
            this.UserLikes = new HashSet<UserLike>();
        }
        [Key]
        public int User_ID { get; set; }
        public string User_Email { get; set; }
        public string User_Password { get; set; }
        public System.DateTime User_SignUpDate { get; set; }
        public int UserType_ID { get; set; }
        public string User_Name { get; set; }

        [JsonIgnore]
        public virtual UserType UserType { get; set; }
        [JsonIgnore]

        public virtual ICollection<UserComment> UserComments { get; set; }
        [JsonIgnore]

        public virtual ICollection<UserLike> UserLikes { get; set; }
    }
}
